sudo: required
services:
 - docker

before_install:
 - docker build -t jasbeer1988/docker-react -f Dockerfile.dev .

script:
 - docker run jasbeer1988/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "docker"
 env: "Docker-env"
 bucket_name: "elasticbeanstalk-us-east-1-810861111654"
 bucket_path: "docker"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_SECURE_KEY"
